### ISSUE TITLE
Add examples for Ingress

### ISSUE THREAD

**Issue by alexellis** [alexellis/expressjs-k8s#2]
Add 3x examples for Ingress:

* Matching any IP
* Matching a single domain name - without TLS (express.example.com)
* Matching a single domain name with TLS (express.example.com) - use Ingress annotations from cert-manager to indicate the certificate should be provisioned automatically from LetsEncrypt. Add a staging HTTP01 Issuer definition.

**Comment by utsavanand2** [comment]
I'll take this up :)

**Comment by alexellis** [comment]
Thank you 👍

**Comment by smcelhinney** [comment]
If @utsavanand2 can't get to this, I can pick it up, lmk 👍 !

**Comment by utsavanand2** [comment]
PR [#3](https://github.com/alexellis/expressjs-k8s/pull/3) Resolves this issue
